### ISSUE TITLE
Determine the technical constraints for HTML5 uploading

### ISSUE THREAD

**Issue by camwest** [vit-backups/vit#1]
## TODO
- [x] can we upload folders
- [ ] can we get the file name of an uploaded folder
- [ ] determine file upload limit (file size, number of selected files)

**Comment by camwest** [comment]
We can only upload folders in Chrome, Firefox, Safari, and IE only support individual files
